export const ErrorCodes = {
  SUCCESS: "SUCCESS",

  // Provider/router
  PROVIDER_NOT_CONFIGURED: "PROVIDER_NOT_CONFIGURED",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  MODEL_NOT_FOUND: "MODEL_NOT_FOUND",
  AUTH_FAILED: "AUTH_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",
  TIMEOUT: "TIMEOUT",
  INVALID_PARAMS: "INVALID_PARAMS",
  INTERNAL_PROVIDER_ERROR: "INTERNAL_PROVIDER_ERROR",

  // DB layer
  DB_UNAVAILABLE: "DB_UNAVAILABLE",
  NOT_FOUND: "NOT_FOUND",
  WRITE_CONFLICT: "WRITE_CONFLICT",
  SERIALIZATION_FAILED: "SERIALIZATION_FAILED",

  // Retrieval
  INDEX_NOT_READY: "INDEX_NOT_READY",
  INDEX_NOT_FOUND: "INDEX_NOT_FOUND",
  QUERY_EMBEDDING_FAILED: "QUERY_EMBEDDING_FAILED",
  RETRIEVAL_FAILED: "RETRIEVAL_FAILED",

  // Clipboard/screenshot
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UNKNOWN_CAPABILITY: "UNKNOWN_CAPABILITY",
  PATH_OUT_OF_SCOPE: "PATH_OUT_OF_SCOPE",
  CLIPBOARD_UNAVAILABLE: "CLIPBOARD_UNAVAILABLE",
  UNSUPPORTED_CONTENT: "UNSUPPORTED_CONTENT",
  IMAGE_NOT_FOUND: "IMAGE_NOT_FOUND",
  IMAGE_DECODE_FAILED: "IMAGE_DECODE_FAILED",
  OCR_FAILED: "OCR_FAILED",
  VISION_MODEL_UNAVAILABLE: "VISION_MODEL_UNAVAILABLE",

  // Orchestrator/task runner
  CONTEXT_LOAD_FAILED: "CONTEXT_LOAD_FAILED",
  GENERATION_FAILED: "GENERATION_FAILED",
  PERSIST_FAILED: "PERSIST_FAILED",
  RETRIEVAL_FAILED_ORCH: "RETRIEVAL_FAILED",

  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_TIMEOUT: "TASK_TIMEOUT",
  TASK_EXECUTION_FAILED: "TASK_EXECUTION_FAILED",
  TASK_CANCELLED: "TASK_CANCELLED"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

